// UI code must never panic in production: unwraps here crash the whole app.
// Use let-else / if-let with early return instead (see ai_collaboration.md,
// "Robustness roadmap"). Tests may still unwrap freely.
#![cfg_attr(not(test), warn(clippy::unwrap_used))]

pub mod menu;
pub mod inspector;
pub mod inspector_camera;
pub mod inspector_property;
pub mod inspector_layer;
pub mod effects_library;
pub mod effects_controls;
pub mod timeline;
pub mod viewport;
pub mod viewport_state;
pub mod viewport_overlays;
pub mod viewport_canvas;
pub mod viewport_camera_3d;
pub mod export_dialog;
pub mod audio_meter;
pub mod history_panel;
pub mod demo_scene;
pub mod welcome;
pub mod drop_import;
pub mod new_comp_dialog;
pub mod preferences_dialog;
pub mod project_io;
pub mod icons;
pub mod toolbar;
pub mod project_panel;
pub mod flowchart;
pub mod character_panel;
pub mod paragraph_panel;
pub mod tracker_panel;
pub mod render_queue;
pub mod transport_panel;
pub mod paint_panel;
pub mod comp_settings_dialog;
pub mod align_panel;
pub mod shortcuts_dialog;
pub mod marker_panel;
pub mod audio_panel;
pub mod time_remap_panel;
pub mod mask_panel;
pub mod expression_panel;
pub mod essential_graphics;
pub mod content_aware_fill;
pub mod metadata_panel;
pub mod scripting_console;
pub mod workspace_manager;
pub mod color_management;
pub mod flowchart_inspector;
pub mod camera_views;
pub mod lumetri_color;
pub mod cc_libraries;
pub mod font_picker;
pub mod render_presets;
pub mod audio_mixer;
pub mod speed_graph_options;
pub mod camera_light_options;
pub mod layer_styles;
pub mod graph_editor;
pub mod theme;
pub mod notification;
pub mod focus;
pub mod shortcuts;
pub mod command_palette;
pub mod flowchart_graph;
pub mod viewport_inline_editor;
pub mod viewport_minimap;
pub mod align_hud;
pub mod camera_dof_hud;
pub mod sequence_layers_dialog;
pub mod precompose_dialog;
pub mod recovery_dialog;
pub mod panel_animation;
pub mod custom_widgets;


