#![allow(dead_code)]
use crate::core::continuous_rasterizer::multiply_matrix_3x3;

/// Shape Repeater configuration options matching After Effects Shape Repeater contents.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ShapeRepeaterOptions {
    pub copies: u32,
    pub offset: f32,
    pub position_offset: [f32; 2],
    pub scale_offset: [f32; 2], // Percentage multiplier per copy (1.0 = 100%)
    pub rotation_offset_deg: f32,
    pub start_opacity: f32,
    pub end_opacity: f32,
    pub composite_below: bool,
}

impl Default for ShapeRepeaterOptions {
    fn default() -> Self {
        Self {
            copies: 3,
            offset: 0.0,
            position_offset: [100.0, 0.0],
            scale_offset: [1.0, 1.0],
            rotation_offset_deg: 0.0,
            start_opacity: 1.0,
            end_opacity: 1.0,
            composite_below: true,
        }
    }
}

/// A evaluated copy instance generated by the Shape Repeater.
#[derive(Debug, Clone, Copy)]
pub struct RepeaterCopyInstance {
    pub copy_index: u32,
    pub transform_matrix: [[f32; 3]; 3],
    pub opacity: f32,
}

/// Evaluates array of 2D 3x3 transformation matrices and opacities for all repeated shape instances.
pub fn evaluate_shape_repeater(options: &ShapeRepeaterOptions) -> Vec<RepeaterCopyInstance> {
    if options.copies == 0 {
        return Vec::new();
    }

    let mut instances = Vec::with_capacity(options.copies as usize);
    let total = options.copies as f32;

    for i in 0..options.copies {
        let copy_idx = i as f32 + options.offset;

        // Position offset per copy
        let px = options.position_offset[0] * copy_idx;
        let py = options.position_offset[1] * copy_idx;

        // Scale compound per copy
        let sx = options.scale_offset[0].powf(copy_idx);
        let sy = options.scale_offset[1].powf(copy_idx);

        // Rotation offset per copy
        let rot_deg = options.rotation_offset_deg * copy_idx;
        let rad = rot_deg.to_radians();
        let cos = rad.cos();
        let sin = rad.sin();

        // 3x3 Matrix construction: Scale -> Rotate -> Translate
        let s_rot = [
            [sx * cos, -sy * sin, 0.0],
            [sx * sin, sy * cos, 0.0],
            [0.0, 0.0, 1.0],
        ];

        let t_pos = [
            [1.0, 0.0, px],
            [0.0, 1.0, py],
            [0.0, 0.0, 1.0],
        ];

        let matrix = multiply_matrix_3x3(&t_pos, &s_rot);

        // Opacity interpolation across copies
        let opacity_t = if options.copies > 1 { i as f32 / (total - 1.0) } else { 0.0 };
        let opacity = options.start_opacity + (options.end_opacity - options.start_opacity) * opacity_t;

        instances.push(RepeaterCopyInstance {
            copy_index: i,
            transform_matrix: matrix,
            opacity: opacity.clamp(0.0, 1.0),
        });
    }

    if !options.composite_below {
        instances.reverse();
    }

    instances
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_shape_repeater_linear_copies() {
        let options = ShapeRepeaterOptions {
            copies: 4,
            offset: 0.0,
            position_offset: [50.0, 0.0],
            scale_offset: [1.0, 1.0],
            rotation_offset_deg: 0.0,
            start_opacity: 1.0,
            end_opacity: 1.0,
            composite_below: true,
        };

        let instances = evaluate_shape_repeater(&options);
        assert_eq!(instances.len(), 4);

        // Copy 0: X = 0
        assert_eq!(instances[0].transform_matrix[0][2], 0.0);
        // Copy 1: X = 50
        assert_eq!(instances[1].transform_matrix[0][2], 50.0);
        // Copy 3: X = 150
        assert_eq!(instances[3].transform_matrix[0][2], 150.0);
    }
}
